### PR TITLE
Updated Dependencies

### PR DESCRIPTION
**Pull request by resslr**
Added more dependencies as required, and will open new pull request soon for wallpaper setup instructions

### CODE REVIEW

**Review by resslr — COMMENTED** [review]
Added Package Managers for dkjson, and all other needed modules

**Comment by resslr** [comment]
@kosorin This but can you add awesomewm as a dependency, I can't edit existing pull requests

**Comment by kosorin** [comment]
Thank you. The readme is a little bit outdated and needs to be reworked anyway.

**Comment by resslr** [comment]
Yw, thank you!

**Pull request merged**
