### PR TITLE
Auto Installer Script

### PR DESCRIPTION
**Pull request by resslr**
* update: auto-installer part one

* update: auto installer script and README.md part 2

* Fix localsend rule

* Fix "+" button

* Remove tag name prefix

* New keybinding to move client to relative tag

* Change "Move client to previous/next tag" keybinding

---------

### CODE REVIEW

**Comment by kosorin** [comment]
I don't think it's a good idea to force users to use `yay` instead of other AUR helpers. I use `paru`, for example. Also it's better to install all packages at once (or most, if possible) rather than installing them one by one as you do.

Also, for example, you install `dkjson` using luarocks. But arch has the `lua-dkjson` package in the extra repository.

Install nvidia packages? Why.Let the user to manage their system.

So in the end, I'm not convinced that this install script is even necessary.

It would be nice if the install script simply offered to install the listed dependencies and nothing else.

**Comment by resslr** [comment]
> I don't think it's a good idea to force users to use `yay` instead of other AUR helpers. I use `paru`, for example. Also it's better to install all packages at once (or most, if possible) rather than installing them one by one as you do.
> 
> Also, for example, you install `dkjson` using luarocks. But arch has the `lua-dkjson` package in the extra repository.
> 
> Install nvidia packages? Why.Let the user to manage their system.
> 
> So in the end, I'm not convinced that this install script is even necessary.
> 
> It would be nice if the install script simply offered to install the listed dependencies and nothing else.

I can change the package manager to paru and have the installation of packages be an optional thing and remove nvidia

**Comment by resslr** [comment]
@kosorin updated

**Comment by resslr** [comment]
I don't think it's a good idea to force users to use yay instead of other AUR helpers. I use paru, for example. Also it's better to install all packages at once (or most, if possible) rather than installing them one by one as you do.
So in the end, I'm not convinced that this install script is even necessary. -- Agreed at this point honestly after trying to use it in a genuine installation it is just not nessecary and it is actually better to install it manually for experience and fun

**Pull request closed without merging**
