### PR TITLE
Built out auxiliary key names and created VIM key groups

### PR DESCRIPTION
**Pull request by PhilomathJ**
### Auxiliary key names

I added key names for keys like Scroll Lock, PgUp/DnPrint Screen since I never remember the actual keycodes for them

### Vim navigation key groups

I use the Vim navigation keys in some key bindings, so I added easy up/down and left/right key groups for clarity

### CODE REVIEW

**Comment by kosorin** [comment]
Can you split this PR? I'll accept "key groups" and "key names".

Layout icons (colors) don't fit the style very well. Could you change them to svgs (since there is already svg) and add `class` attributes, so it can use theme colors. See the floating icon:

https://github.com/kosorin/awesome-rice/blob/5ebc510f9862fc4042df8269de026badc83764c2/theme/icons/layouts/floating.svg#L6-L7

and theme

https://github.com/kosorin/awesome-rice/blob/5ebc510f9862fc4042df8269de026badc83764c2/theme/theme.lua#L837-L846

**Comment by PhilomathJ** [comment]
Removed the commit with the extra layouts

**Comment by PhilomathJ** [comment]
I will create a new PR with the layout icon changes you mentioned

**Comment by PhilomathJ** [comment]
# Thanks!

**Pull request merged**
