### PR TITLE
auto-installer update

### PR DESCRIPTION
**Pull request by resslr**
Review this code before accepting, could be unstable and a second pair of eyes doesn't hurt -rebase

### CODE REVIEW

**Comment by resslr** [comment]
some commits are because of the update you did while I was making this

**Comment by kosorin** [comment]
It's your branch and instead of merging, you can rebase

**Comment by resslr** [comment]
> It's your branch and instead of merging, you can rebase

Is there something I need to fix?

**Comment by resslr** [comment]
one sec reopening

**Pull request closed without merging**
